[package]
name = "pawcon"
version = "0.1.0"
edition = "2021"

[dependencies]
iced =  { version="0.7",features = ["canvas", "tokio", "debug"] }
once_cell = "1.16.0"
chrono = { version = "0.4", features = ["unstable-locales"] }
hidapi = "1.5.0"

[dependencies.hf2]
version = "0.3.3"
path = "lib/hf2"
